name: local_mlflow_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - ipython
  - notebook=6.4.6
  - jupyter=1.0.0
  - hydra-core=1.0.6
  - matplotlib=3.5.0
  - pandas=1.3.4
  - pip=21.3.1
